# Generated by Django 5.2.7 on 2025-10-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_engagement_owner_post_engagement_viewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='owner_post',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.post'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.post'),
        ),
    ]
