# Generated by Django 5.2.7 on 2025-10-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='comment_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.post'),
        ),
    ]
