# Generated by Django 5.2.7 on 2025-10-26 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_post_comment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='comment_text',
            field=models.TextField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engagement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post_Comment',
        ),
    ]
